import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import NavBar from "../components/navbar/NavBar";
import dynamic from "next/dynamic";
import { SmoothScroll } from "../components/ui/SmoothScroll";
import { Providers } from "./Providers";
import { TransitionProvider } from "../components/products/TransitionContext";

// const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Providers>
          <SmoothScroll>
            <NavBar />
            {children}
          </SmoothScroll>
        </Providers>
      </body>
    </html>
  );
}
